language: objective-c

before_install: 
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script: 
- xctool clean build test -project RSTCoreDataKit.xcodeproj -scheme RSTCoreDataKit -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO
